"use client";
import { useEffect, useMemo, useState } from "react";
import { SearchIcon } from "@/components/icons";
import { PlatformBadge } from "@/components/platform-badge";
import { getMessages, subscribeToConversations, subscribeToMessages } from "@/lib/data";
import type { Conversation, Message, Platform } from "@/types/database";
type Filter = "all" | Platform;
const time = (value: string) => new Intl.DateTimeFormat("en", { hour: "numeric", minute: "2-digit" }).format(new Date(value));
const listTime = (value: string) => { const date = new Date(value); return date.toDateString() === new Date().toDateString() ? time(value) : new Intl.DateTimeFormat("en", { month:"short", day:"numeric" }).format(date); };
function Avatar({ conversation }: { conversation: Conversation }) { const initials = (conversation.user_name || "Unknown user").split(" ").map((part) => part[0]).slice(0,2).join(""); return <div className="relative grid h-11 w-11 shrink-0 place-items-center rounded-full bg-indigo-100 text-sm font-bold text-indigo-700">{initials}<span className="absolute -bottom-0.5 -right-0.5 rounded-md border-2 border-white bg-white"><PlatformBadge platform={conversation.platform} compact /></span></div>; }
export function ConversationDashboard({ initialConversations, demo }: { initialConversations: Conversation[]; demo: boolean }) {
  const [conversations,setConversations] = useState(initialConversations); const [selected,setSelected] = useState<Conversation|null>(initialConversations[0] ?? null); const [messages,setMessages] = useState<Message[]>([]); const [loading,setLoading] = useState(Boolean(selected)); const [error,setError] = useState(""); const [search,setSearch] = useState(""); const [filter,setFilter] = useState<Filter>("all"); const [showChat,setShowChat] = useState(false);
  useEffect(() => { if (!selected) return; let active=true; setLoading(true); setError(""); getMessages(selected.id).then((items) => { if(active) setMessages(items); }).catch(() => { if(active) setError("Could not load this conversation."); }).finally(() => { if(active) setLoading(false); }); return () => { active=false; }; }, [selected]);
  useEffect(() => subscribeToMessages((message) => {
    if (message.conversation_id === selected?.id) setMessages((current) => current.some((item) => item.id === message.id) ? current : [...current, message]);
    setConversations((current) => current.map((item) => item.id === message.conversation_id ? { ...item, last_message: message.message, last_message_at: message.created_at, updated_at: message.created_at } : item).sort((a,b) => Date.parse(b.last_message_at) - Date.parse(a.last_message_at)));
  }), [selected?.id]);
  useEffect(() => subscribeToConversations((conversation) => {
    setConversations((current) => [conversation, ...current.filter((item) => item.id !== conversation.id)].sort((a,b) => Date.parse(b.last_message_at) - Date.parse(a.last_message_at)));
    setSelected((current) => current?.id === conversation.id ? conversation : current);
  }), []);
  const filtered = useMemo(() => conversations.filter((item) => (filter === "all" || item.platform === filter) && `${item.user_name ?? ""} ${item.last_message ?? ""}`.toLowerCase().includes(search.toLowerCase())), [filter,conversations,search]);
  const select = (item: Conversation) => { setSelected(item); setShowChat(true); };
  return <div className="flex h-full flex-col p-3 pt-16 sm:p-5 sm:pt-16 md:p-7"><header className="mb-5 flex items-end justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.18em] text-indigo-500">Inbox</p><h1 className="text-2xl font-bold tracking-tight text-slate-900">Conversations</h1><p className="mt-1 text-sm text-slate-500">Review your Instagram and Facebook chatbot history.</p></div>{demo && <span className="hidden rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700 ring-1 ring-amber-200 sm:block">Demo data</span>}</header>
    <div className="min-h-0 flex-1 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="grid h-full md:grid-cols-[350px_minmax(0,1fr)] lg:grid-cols-[390px_minmax(0,1fr)]">
      <section className={`${showChat ? "hidden md:flex" : "flex"} min-w-0 flex-col border-r border-slate-200`}><div className="border-b border-slate-100 p-4"><label className="flex items-center gap-2 rounded-xl bg-slate-100 px-3 py-2.5 text-slate-500 ring-indigo-200 focus-within:ring-2"><SearchIcon className="h-4 w-4" /><input aria-label="Search conversations" value={search} onChange={(e) => setSearch(e.target.value)} className="w-full bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400" placeholder="Search conversations" /></label><div className="mt-3 flex gap-2">{(["all","instagram","facebook"] as Filter[]).map((item) => <button key={item} onClick={() => setFilter(item)} className={`rounded-lg px-3 py-1.5 text-xs font-semibold capitalize transition ${filter === item ? "bg-indigo-600 text-white" : "bg-slate-50 text-slate-600 hover:bg-slate-100"}`}>{item}</button>)}</div></div>
        <div className="min-h-0 flex-1 overflow-y-auto">{filtered.length ? filtered.map((item) => <button key={item.id} onClick={() => select(item)} className={`flex w-full gap-3 border-b border-slate-100 p-4 text-left transition hover:bg-slate-50 ${selected?.id === item.id ? "bg-indigo-50/70" : ""}`}><Avatar conversation={item} /><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><strong className="truncate text-sm text-slate-900">{item.user_name}</strong><time className="shrink-0 text-[11px] text-slate-400">{listTime(item.last_message_at)}</time></span><span className="mt-1 block text-[11px]"><PlatformBadge platform={item.platform} /></span><span className="mt-1 block truncate text-xs text-slate-500">{item.last_message}</span></span></button>) : <div className="grid h-48 place-items-center px-8 text-center text-sm text-slate-400">No conversations match your search.</div>}</div>
      </section>
      <section className={`${showChat ? "flex" : "hidden md:flex"} min-w-0 flex-col bg-[#f8fafc]`}>{selected ? <><div className="flex h-[73px] shrink-0 items-center gap-3 border-b border-slate-200 bg-white px-4 sm:px-5"><button onClick={() => setShowChat(false)} className="mr-1 text-xl text-slate-500 md:hidden" aria-label="Back to conversations">←</button><Avatar conversation={selected} /><div><h2 className="text-sm font-bold text-slate-900">{selected.user_name}</h2><div className="mt-1 text-[11px]"><PlatformBadge platform={selected.platform} /></div></div><div className="ml-auto hidden rounded-lg bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700 sm:block">Active</div></div>
        <div className="min-h-0 flex-1 overflow-y-auto bg-[radial-gradient(#dbe2ee_0.7px,transparent_0.7px)] bg-[length:16px_16px] p-4 sm:p-7">{loading ? <div className="space-y-4"><div className="h-14 w-2/3 animate-pulse rounded-2xl bg-slate-200" /><div className="ml-auto h-16 w-3/5 animate-pulse rounded-2xl bg-indigo-100" /></div> : error ? <div className="grid h-full place-items-center text-sm text-rose-500">{error}</div> : messages.length ? <div className="space-y-4">{messages.map((item) => <div key={item.id} className={`flex ${item.sender_type === "bot" ? "justify-end" : "justify-start"}`}><div className={`max-w-[82%] rounded-2xl px-4 py-3 shadow-sm sm:max-w-[68%] ${item.sender_type === "bot" ? "rounded-br-md bg-indigo-600 text-white" : "rounded-bl-md border border-slate-200 bg-white text-slate-700"}`}><p className="text-sm leading-relaxed">{item.message}</p><time className={`mt-1.5 block text-right text-[10px] ${item.sender_type === "bot" ? "text-indigo-200" : "text-slate-400"}`}>{time(item.created_at)}</time></div></div>)}</div> : <div className="grid h-full place-items-center text-sm text-slate-400">No messages in this conversation yet.</div>}</div><div className="border-t border-slate-200 bg-white px-5 py-3 text-center text-xs text-slate-400">Read-only history · Replies are not enabled</div></> : <div className="grid h-full place-items-center text-sm text-slate-400">Select a conversation to view its history.</div>}</section>
    </div></div>
  </div>;
}
